  spring:
    h2:
     console:
       enabled: true
       path: /h2
    datasource:
           url: jdbc:h2:mem:productCommandDb
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
       group-id: products1-group
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  camel:
    component:
      kafka:
       brokers: localhost:9092
  server:
   port: 8081

